#!/usr/bin/env python
"""Verify every upstream repository URL in source_repositories/MANIFEST.yaml.

For each manifest entry this tool runs ``git ls-remote --symref`` against
the recorded canonical URL to confirm:

* the remote exists and is reachable,
* the default branch recorded in the manifest matches upstream,
* the upstream HEAD commit (for default-branch movers).

Results are written to ``source_repositories/UPSTREAM_VERIFICATION.yaml``
(machine-readable) and summarized on stdout. Failures are reported
honestly — an unreachable/moved URL is never silently marked verified.

Run from the repository root::

    .venv-fresh2/Scripts/python tools/verify_upstream_repos.py [--timeout 20]

Network access is required; with no network the tool exits non-zero and
leaves any previous verification report untouched.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "source_repositories" / "MANIFEST.yaml"
REPORT = ROOT / "source_repositories" / "UPSTREAM_VERIFICATION.yaml"


def _load_manifest_entries() -> list[dict[str, str]]:
    """Minimal manifest reader (name/category/canonical_url/branch)."""
    entries: list[dict[str, str]] = []
    category = ""
    current: dict[str, str] | None = None
    for raw in MANIFEST.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        if not line or line.startswith("#"):
            continue
        if not line.startswith((" ", "-")):
            category = line.rstrip(":").strip()
            continue
        stripped = line.strip()
        if stripped.startswith("- name:"):
            if current is not None:
                entries.append(current)
            current = {"category": category, "name": stripped.split(":", 1)[1].strip().strip('"')}
            continue
        if current is not None and ":" in stripped:
            key, _, value = stripped.partition(":")
            current.setdefault(key.strip(), value.strip().strip('"'))
    if current is not None:
        entries.append(current)
    return entries


def _ls_remote(url: str, timeout: int) -> tuple[bool, str, str]:
    """Return (ok, default_branch, head_or_error) for a remote URL."""
    try:
        proc = subprocess.run(
            ["git", "ls-remote", "--symref", url, "HEAD"],
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except (subprocess.TimeoutExpired, OSError) as exc:
        return False, "", f"error: {exc}"
    if proc.returncode != 0:
        return False, "", (proc.stderr or "unknown error").strip().splitlines()[-1][:160]
    branch = ""
    commit = ""
    for line in proc.stdout.splitlines():
        match = re.match(r"ref:\s+refs/heads/(\S+)\tHEAD", line.strip())
        if match:
            branch = match.group(1)
        elif "\tHEAD" in line:
            commit = line.split("\t")[0]
    return True, branch or "unknown", commit or "unknown"


def _safe_yaml(value: str) -> str:
    if value and re.search(r"[^A-Za-z0-9_./:\-]", value):
        return '"' + value.replace('"', '\\"') + '"'
    return value or '""'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--timeout", type=int, default=20, help="Per-repo network timeout seconds.")
    args = parser.parse_args()

    if not MANIFEST.exists():
        print(f"error: {MANIFEST} not found", file=sys.stderr)
        return 1

    entries = _load_manifest_entries()
    if not entries:
        print("error: no manifest entries parsed", file=sys.stderr)
        return 1

    now = _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0).isoformat()
    lines: list[str] = [
        "# ORION upstream-URL verification report",
        "# Generated by tools/verify_upstream_repos.py — DO NOT EDIT BY HAND.",
        f"# last_verified: {now}",
        "",
        "manifest_version: 1",
        f"verified_at: {now}",
        f"total_checked: {len(entries)}",
        "",
        "repositories:",
    ]

    reachable = 0
    branch_mismatches: list[str] = []
    for entry in entries:
        name = entry.get("name", "unknown")
        url = entry.get("canonical_url", "")
        recorded_branch = entry.get("branch", "unknown")
        if not url.startswith("https://"):
            ok, up_branch, detail = False, "", "no canonical URL recorded"
        else:
            ok, up_branch, detail = _ls_remote(url, args.timeout)
        if ok:
            reachable += 1
            if recorded_branch not in ("unknown", "", "n/a") and up_branch != recorded_branch:
                branch_mismatches.append(f"{name}: manifest={recorded_branch} upstream={up_branch}")
        status = "reachable" if ok else "unreachable"
        lines.append(f"  - name: {name}")
        lines.append(f"    category: {entry.get('category', 'unknown')}")
        lines.append(f"    canonical_url: {_safe_yaml(url)}")
        lines.append(f"    manifest_branch: {_safe_yaml(recorded_branch)}")
        lines.append(f"    upstream_default_branch: {_safe_yaml(up_branch)}")
        lines.append(f"    upstream_head: {_safe_yaml(detail)}")
        lines.append(f"    status: {status}")
        lines.append("")

    lines.append("summary:")
    lines.append(f"  reachable: {reachable}")
    lines.append(f"  unreachable: {len(entries) - reachable}")
    lines.append(f"  branch_mismatches: {len(branch_mismatches)}")
    lines.append("")
    if branch_mismatches:
        lines.append("branch_mismatch_details:")
        for item in branch_mismatches:
            lines.append(f"  - {item}")
        lines.append("")

    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"verified {reachable}/{len(entries)} upstream URLs reachable")
    print(f"branch mismatches: {len(branch_mismatches)}")
    for item in branch_mismatches:
        print(f"  MISMATCH {item}")
    print(f"wrote {REPORT}")
    return 0 if reachable == len(entries) else 2


if __name__ == "__main__":
    sys.exit(main())